### ISSUE TITLE
Changes in Julia 0.51

### ISSUE THREAD

**Issue by ptoche** [matthieugomez/AiyagariContinuousTime.jl#2]
Hi Matthieu,

I wanted to run your code, but faced a couple of problems. First, I was informed that ``Base.SparseMatrix`` was deprecated and asked to use ``Base.SparseArrays`` instead. I made the changes and Julia stopped complaining. Secondly, I'm getting a bunch of messages like this one:

    WARNING: Method definition forward(AbstractArray{T<:Any, 1}, AbstractArray{T<:Any, 1}, AbstractArray{T<:Any, 1}, AbstractArray{T<:Any, 1}) in module AiyagariContinuousTime at /Users/.../julia/aiyagari/kolmogorovforward/kolmogorov.jl:119 overwritten at /Users/.../julia/aiyagari/kolmogorovforward/kolmogorov.jl:120.

I haven't used Julia before, so I'm quite lost.

Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

**Comment by matthieugomez** [comment]
Thanks. I have just updated the package and removed the code for kolmogorov forward, since this package is now focused on solving the Aiyagari Model. This solves your problem.

**Comment by ptoche** [comment]
Thanks Matthieu for your prompt reply. I was probably doing a couple of silly things, e.g. I had 

    cd("path/to/files/")
    include("filename.jl")

but that wasn't working. When I changed it to:

    include("path/to/files/filename.jl")

It started to work. 

The examples of the ``readme`` file worked. Several problems I had initially seem to have been related to Atom/Juno and my incompetence. 

Eventually I was also able to save a plot in an external file, so that's great! After assigning ``p`` to the plot, with:

    draw(PDF("/Users/aiyagari-plots/test.pdf", 800px, 400px), p)

Matter closed! Thanks.
